SET search_path TO prj5;

-- (Opcional) domínios/tipos
CREATE TYPE TP_CRITERIO AS ENUM ('INCLUSAO','EXCLUSAO');

-- Sequences (MAD: SQ_)
CREATE SEQUENCE SQ_PROJETO;
CREATE SEQUENCE SQ_ARTIGO;
CREATE SEQUENCE SQ_AUTOR;
CREATE SEQUENCE SQ_REVISOR;
CREATE SEQUENCE SQ_CRITERIO;
CREATE SEQUENCE SQ_TRIAGEM;
CREATE SEQUENCE SQ_AVALIACAO;
CREATE SEQUENCE SQ_NOTA;
CREATE SEQUENCE SQ_REFERENCIA;
CREATE SEQUENCE SQ_KEYWORD;
CREATE SEQUENCE SQ_TAXONOMIA;
