SET search_path TO prj5;

-- Índices úteis a consultas (tendências e triagem)
CREATE INDEX IDX_ARTIGO_PROJ_ANO ON TB_ARTIGO (ID_PROJETO, AN_ANO);
CREATE INDEX IDX_TRIAGEM_ARTIGO   ON TB_TRIAGEM(ID_ARTIGO);
CREATE INDEX IDX_TRIAGEM_REVISOR  ON TB_TRIAGEM(ID_REVISOR);
