SET search_path TO prj5;

DROP VIEW IF EXISTS VW_ARTIGO_PUBLICO CASCADE;
DROP MATERIALIZED VIEW IF EXISTS VM_TENDENCIAS_ANO_KEY;

CREATE VIEW VW_ARTIGO_PUBLICO AS
SELECT a.ID_ARTIGO, a.NO_TITULO, a.AN_ANO, a.NO_VENUE, p.NO_PROJETO,
       (SELECT string_agg(au.NO_AUTOR, ', ' ORDER BY ra.NU_ORDEM)
          FROM RL_ARTIGO_AUTOR ra JOIN TB_AUTOR au ON au.ID_AUTOR=ra.ID_AUTOR
         WHERE ra.ID_ARTIGO=a.ID_ARTIGO) AS NO_AUTORES
FROM TB_ARTIGO a
JOIN TB_PROJETO p ON p.ID_PROJETO=a.ID_PROJETO;

CREATE MATERIALIZED VIEW VM_TENDENCIAS_ANO_KEY AS
SELECT a.AN_ANO, k.NO_KEYWORD, COUNT(*) AS QT
FROM TB_ARTIGO a
JOIN RL_ARTIGO_KEYWORD ak ON ak.ID_ARTIGO=a.ID_ARTIGO
JOIN TB_KEYWORD k ON k.ID_KEYWORD=ak.ID_KEYWORD
GROUP BY a.AN_ANO, k.NO_KEYWORD;

CREATE INDEX IDX_VM_TEND_ANO ON VM_TENDENCIAS_ANO_KEY(AN_ANO, NO_KEYWORD);
