SET search_path TO prj5;

SELECT SP_SET_CONTEXT_USUARIO_APLICACAO('pesquisador@uni.br');

INSERT INTO TB_PROJETO (NO_PROJETO) VALUES ('REVISAO-ML-2025');            -- ID 1
INSERT INTO TB_ARTIGO (ID_PROJETO, NO_TITULO, AN_ANO, NO_VENUE)
VALUES (1,'APRENDIZADO DE MAQUINA EM SAUDE',2024,'JOURNAL X');             -- ID 1

INSERT INTO TB_AUTOR (NO_AUTOR) VALUES ('ANA LIMA');                       -- ID 1
INSERT INTO RL_ARTIGO_AUTOR (ID_ARTIGO, ID_AUTOR, NU_ORDEM) VALUES (1,1,1);

INSERT INTO TB_KEYWORD (NO_KEYWORD) VALUES ('MACHINE LEARNING');           -- ID 1
INSERT INTO RL_ARTIGO_KEYWORD (ID_ARTIGO, ID_KEYWORD) VALUES (1,1);

REFRESH MATERIALIZED VIEW VM_TENDENCIAS_ANO_KEY;
