-- Consultas Avançadas
-- C1: Consulta revisões com quantidade de rejeições acima da média geral de avaliações
SELECT 
    R.DS_TITULO AS REVISAO,
    COUNT(DISTINCT A.ID_ARTIGO) AS QT_ARTIGOS_REJEITADOS,
    COUNT(AV.ID_AVALIACAO) AS QT_AVALIACOES_REJEITADAS
FROM TB_REVISAO R
JOIN TB_AVALIACAO AV ON R.ID_REVISAO = AV.ID_REVISAO
JOIN TB_ARTIGO A ON AV.ID_ARTIGO = A.ID_ARTIGO
WHERE AV.ST_AVALIACAO = 'REJEITADO'
GROUP BY R.DS_TITULO
HAVING COUNT(DISTINCT A.ID_ARTIGO) > (
    SELECT AVG(QT)
    FROM (
        SELECT COUNT(DISTINCT ID_ARTIGO) AS QT
        FROM TB_AVALIACAO
        WHERE ST_AVALIACAO = 'REJEITADO'
        GROUP BY ID_REVISAO
    ) AS X
)
ORDER BY QT_ARTIGOS_REJEITADOS DESC;


-- C2: Consulta pesquisadores com mais revisões que a média
SELECT P.DS_NOME, COUNT(RR.ID_REVISAO) AS QT_REVISOES
FROM TB_PESQUISADOR P
JOIN RL_PESQUISADOR_REVISAO RR ON P.ID_PESQUISADOR = RR.ID_PESQUISADOR
JOIN TB_REVISAO R ON RR.ID_REVISAO = R.ID_REVISAO
GROUP BY P.DS_NOME
HAVING COUNT(RR.ID_REVISAO) > (
    SELECT AVG(QT) FROM (
        SELECT COUNT(*) AS QT FROM RL_PESQUISADOR_REVISAO GROUP BY ID_PESQUISADOR
    ) T
);

-- C3: Consulta artigos com valor médio de estatísticas acima da média geral
SELECT A.DS_TITULO, AVG(E.VL_VALOR) AS MEDIA_ARTIGO, RP.DS_NOME AS REPOSITORIO
FROM TB_ARTIGO A
JOIN TB_ESTATISTICA E ON A.ID_ARTIGO = E.ID_ARTIGO
JOIN TB_REPOSITORIO RP ON A.ID_REPOSITORIO = RP.ID_REPOSITORIO
GROUP BY A.DS_TITULO, RP.DS_NOME
HAVING AVG(E.VL_VALOR) > (SELECT AVG(VL_VALOR) FROM TB_ESTATISTICA);

-- C4: Revisões onde todos os artigos foram aprovados
SELECT R.DS_TITULO
FROM TB_REVISAO R
JOIN TB_AVALIACAO AV ON R.ID_REVISAO = AV.ID_REVISAO
JOIN TB_ARTIGO A ON AV.ID_ARTIGO = A.ID_ARTIGO
GROUP BY R.DS_TITULO
HAVING MIN(AV.ST_AVALIACAO) = 'APROVADO';

-- C5: Constula pesquisadores com revisões que possuem mais critérios do que a média geral
SELECT 
    P.DS_NOME AS PESQUISADOR,
    R.DS_TITULO AS REVISAO,
    COUNT(DISTINCT C.ID_CRITERIO) AS QT_CRITERIOS
FROM TB_PESQUISADOR P
JOIN RL_PESQUISADOR_REVISAO PR ON P.ID_PESQUISADOR = PR.ID_PESQUISADOR
JOIN TB_REVISAO R ON PR.ID_REVISAO = R.ID_REVISAO
JOIN TB_CRITERIO C ON R.ID_REVISAO = C.ID_REVISAO
GROUP BY P.DS_NOME, R.DS_TITULO
HAVING COUNT(DISTINCT C.ID_CRITERIO) > (
    SELECT AVG(QT)
    FROM (
        SELECT COUNT(DISTINCT ID_CRITERIO) AS QT
        FROM TB_CRITERIO
        GROUP BY ID_REVISAO
    ) AS X
)
ORDER BY QT_CRITERIOS DESC;


-- C6: Constula pesquisadores por número de avaliações e artigos
SELECT 
    P.DS_NOME AS PESQUISADOR,
    COUNT(DISTINCT A.ID_ARTIGO) AS QT_ARTIGOS_AVALIADOS,
    COUNT(AV.ID_AVALIACAO) AS QT_AVALIACOES,
    RANK() OVER (ORDER BY COUNT(DISTINCT A.ID_ARTIGO) DESC) AS POSICAO
FROM TB_PESQUISADOR P
JOIN TB_AVALIACAO AV 
    ON P.ID_PESQUISADOR = AV.ID_PESQUISADOR_AVALIADOR_1
JOIN TB_ARTIGO A 
    ON AV.ID_ARTIGO = A.ID_ARTIGO
WHERE A.CD_ANO_PUBLICACAO >= 2020
GROUP BY P.DS_NOME
ORDER BY QT_ARTIGOS_AVALIADOS DESC;


-- C7: Consulta repositórios com mais artigos avaliados do que a média geral
SELECT 
    RP.DS_NOME AS REPOSITORIO,
    COUNT(DISTINCT A.ID_ARTIGO) AS QT_ARTIGOS_AVALIADOS
FROM TB_REPOSITORIO RP
JOIN TB_ARTIGO A ON RP.ID_REPOSITORIO = A.ID_REPOSITORIO
JOIN TB_AVALIACAO AV ON A.ID_ARTIGO = AV.ID_ARTIGO
GROUP BY RP.DS_NOME
HAVING COUNT(DISTINCT A.ID_ARTIGO) > (
    SELECT AVG(QT)
    FROM (
        SELECT COUNT(DISTINCT A2.ID_ARTIGO) AS QT
        FROM TB_REPOSITORIO RP2
        JOIN TB_ARTIGO A2 ON RP2.ID_REPOSITORIO = A2.ID_REPOSITORIO
        JOIN TB_AVALIACAO AV2 ON A2.ID_ARTIGO = AV2.ID_ARTIGO
        GROUP BY RP2.ID_REPOSITORIO
    ) AS SUB
)
ORDER BY QT_ARTIGOS_AVALIADOS DESC;


-- C8: Consulta artigos com mais de uma avaliação e com repositório
SELECT A.DS_TITULO, RP.DS_NOME, COUNT(AV.ID_AVALIACAO) AS QT_AVALIACOES
FROM TB_ARTIGO A
JOIN TB_AVALIACAO AV ON A.ID_ARTIGO = AV.ID_ARTIGO
JOIN TB_REPOSITORIO RP ON A.ID_REPOSITORIO = RP.ID_REPOSITORIO
GROUP BY A.DS_TITULO, RP.DS_NOME
HAVING COUNT(AV.ID_AVALIACAO) > 1;

-- C9: Consulta pesquisadores com revisões de artigos rejeitados e número de participações
SELECT 
    P.DS_NOME AS PESQUISADOR,
    COUNT(DISTINCT RR.ID_REVISAO) AS QT_REVISOES_REJEITADAS,
    COUNT(AV.ID_AVALIACAO) AS QT_AVALIACOES_REJEITADAS
FROM TB_PESQUISADOR P
JOIN RL_PESQUISADOR_REVISAO RR 
    ON P.ID_PESQUISADOR = RR.ID_PESQUISADOR
JOIN TB_AVALIACAO AV 
    ON RR.ID_REVISAO = AV.ID_REVISAO
WHERE AV.ST_AVALIACAO = 'REJEITADO'
GROUP BY P.DS_NOME
HAVING COUNT(DISTINCT RR.ID_REVISAO) > 0
ORDER BY QT_REVISOES_REJEITADAS DESC;


-- C10: Consulta revisões com mais artigos que a média geral
SELECT 
    R.DS_TITULO AS REVISAO,
    COUNT(DISTINCT A.ID_ARTIGO) AS QT_ARTIGOS,
    AVG(COUNT(DISTINCT A.ID_ARTIGO)) OVER () AS MEDIA_GERAL,
    COUNT(AV.ID_AVALIACAO) AS QT_AVALIACOES
FROM TB_REVISAO R
JOIN TB_AVALIACAO AV ON R.ID_REVISAO = AV.ID_REVISAO
JOIN TB_ARTIGO A ON AV.ID_ARTIGO = A.ID_ARTIGO
GROUP BY R.DS_TITULO
HAVING COUNT(DISTINCT A.ID_ARTIGO) > (
    SELECT AVG(QT)
    FROM (
        SELECT COUNT(DISTINCT ID_ARTIGO) AS QT
        FROM TB_AVALIACAO
        GROUP BY ID_REVISAO
    ) TMP
)
ORDER BY QT_ARTIGOS DESC;
