-- Consultas Intermediárias
-- C1: Consulta total de revisões por pesquisador
SELECT P.DS_NOME, COUNT(RR.ID_REVISAO) AS QT_REVISOES
FROM TB_PESQUISADOR P
JOIN RL_PESQUISADOR_REVISAO RR ON P.ID_PESQUISADOR = RR.ID_PESQUISADOR
JOIN TB_REVISAO R ON RR.ID_REVISAO = R.ID_REVISAO
GROUP BY P.DS_NOME;

-- C2: Consulta número de artigos com avaliação por repositório e ano
SELECT RP.DS_NOME AS REPOSITORIO,
       A.CD_ANO_PUBLICACAO,
       COUNT(DISTINCT A.ID_ARTIGO) AS QT_ARTIGOS_AVALIADOS
FROM TB_REPOSITORIO RP
JOIN TB_ARTIGO A ON RP.ID_REPOSITORIO = A.ID_REPOSITORIO
JOIN TB_AVALIACAO AV ON A.ID_ARTIGO = AV.ID_ARTIGO
GROUP BY RP.DS_NOME, A.CD_ANO_PUBLICACAO
ORDER BY RP.DS_NOME, A.CD_ANO_PUBLICACAO;


-- C3: Consulta número de avaliações por status e pesquisador avaliador
SELECT P.DS_NOME, AV.ST_AVALIACAO, COUNT(*) AS QT_AVALIACOES
FROM TB_PESQUISADOR P
JOIN TB_AVALIACAO AV ON P.ID_PESQUISADOR = AV.ID_PESQUISADOR_AVALIADOR_1
JOIN TB_ARTIGO A ON AV.ID_ARTIGO = A.ID_ARTIGO
GROUP BY P.DS_NOME, AV.ST_AVALIACAO;

-- C4: Consulta revisões com número de critérios e pesquisadores associados
SELECT R.DS_TITULO,
       COUNT(DISTINCT C.ID_CRITERIO) AS QT_CRITERIOS,
       COUNT(DISTINCT PR.ID_PESQUISADOR) AS QT_PESQUISADORES
FROM TB_REVISAO R
JOIN TB_CRITERIO C ON R.ID_REVISAO = C.ID_REVISAO
JOIN RL_PESQUISADOR_REVISAO PR ON R.ID_REVISAO = PR.ID_REVISAO
GROUP BY R.ID_REVISAO
ORDER BY QT_CRITERIOS DESC; 

-- C5: Consulta artigos mais recentes e posição no ranking por ano
SELECT A.DS_TITULO, A.CD_ANO_PUBLICACAO, R.DS_NOME AS REPOSITORIO,
       ROW_NUMBER() OVER (PARTITION BY A.CD_ANO_PUBLICACAO ORDER BY A.CD_ANO_PUBLICACAO DESC) AS POSICAO
FROM TB_ARTIGO A
JOIN TB_REPOSITORIO R ON A.ID_REPOSITORIO = R.ID_REPOSITORIO
JOIN TB_AVALIACAO AV ON A.ID_ARTIGO = AV.ID_ARTIGO
GROUP BY A.ID_ARTIGO, R.DS_NOME;

-- C6: Consulta quantidade de revisões concluídas por pesquisador
SELECT P.DS_NOME, COUNT(R.ID_REVISAO) AS QT_CONCLUIDAS
FROM TB_PESQUISADOR P
JOIN RL_PESQUISADOR_REVISAO RR ON P.ID_PESQUISADOR = RR.ID_PESQUISADOR
JOIN TB_REVISAO R ON RR.ID_REVISAO = R.ID_REVISAO
WHERE R.DT_CONCLUSAO IS NOT NULL
GROUP BY P.ID_PESQUISADOR;

-- C7: Consulta quantidade média de critérios por revisão
SELECT R.DS_TITULO,
       COUNT(DISTINCT C.ID_CRITERIO) AS QT_CRITERIOS,
       AVG(COUNT(DISTINCT C.ID_CRITERIO)) OVER () AS MEDIA_CRITERIOS
FROM TB_REVISAO R
JOIN TB_CRITERIO C ON R.ID_REVISAO = C.ID_REVISAO
JOIN RL_PESQUISADOR_REVISAO PR ON R.ID_REVISAO = PR.ID_REVISAO
GROUP BY R.ID_REVISAO
ORDER BY QT_CRITERIOS DESC;

-- C8: Consulta avaliações mais recentes por artigo
SELECT A.DS_TITULO, AV.ST_AVALIACAO,
       AV.DH_AVALIACAO,
       RANK() OVER (PARTITION BY A.ID_ARTIGO ORDER BY AV.DH_AVALIACAO DESC) AS POSICAO
FROM TB_ARTIGO A
JOIN TB_AVALIACAO AV ON A.ID_ARTIGO = AV.ID_ARTIGO
JOIN TB_REVISAO R ON AV.ID_REVISAO = R.ID_REVISAO;

-- C9: Consulta pesquisadores e número total de artigos avaliados
SELECT P.DS_NOME, COUNT(AV.ID_ARTIGO) AS QT_ARTIGOS_REV
FROM TB_PESQUISADOR P
JOIN TB_AVALIACAO AV ON P.ID_PESQUISADOR = AV.ID_PESQUISADOR_AVALIADOR_1
JOIN TB_ARTIGO A ON AV.ID_ARTIGO = A.ID_ARTIGO
GROUP BY P.DS_NOME;

-- C10: Consulta revisões e número total de artigos associados via avaliação
SELECT R.DS_TITULO, COUNT(DISTINCT AV.ID_ARTIGO) AS QT_ARTIGOS
FROM TB_REVISAO R
JOIN TB_AVALIACAO AV ON R.ID_REVISAO = AV.ID_REVISAO
JOIN TB_ARTIGO A ON AV.ID_ARTIGO = A.ID_ARTIGO
GROUP BY R.DS_TITULO;
