-- Criação das tabelas (TB_)
-- Criação das constraints (PK_, FK_, CK_, UK_)

CREATE TABLE TB_PESQUISADOR (
    ID_PESQUISADOR BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    DS_NOME VARCHAR(150) NOT NULL,
    DS_EMAIL VARCHAR(100) NOT NULL,
    DS_CPF VARCHAR(11) NOT NULL,

    CONSTRAINT PK_PESQUISADOR PRIMARY KEY (ID_PESQUISADOR),
    CONSTRAINT UK_PESQUISADOR_EMAIL UNIQUE (DS_EMAIL),
    CONSTRAINT UK_PESQUISADOR_CPF UNIQUE (DS_CPF)
);

CREATE TABLE TB_REVISAO (
    ID_REVISAO BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    DS_TITULO VARCHAR(255) NOT NULL,
    DS_DESCRICAO VARCHAR(2000),
    DT_INICIO DATE NOT NULL,
    DT_CONCLUSAO DATE,

    CONSTRAINT PK_REVISAO PRIMARY KEY (ID_REVISAO)
);

CREATE TABLE TB_REPOSITORIO (
    ID_REPOSITORIO BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    DS_NOME VARCHAR(255) NOT NULL,
    DS_URL VARCHAR(2000) NOT NULL,
    DT_CRIACAO DATE NOT NULL,

    CONSTRAINT PK_REPOSITORIO PRIMARY KEY (ID_REPOSITORIO)
);

CREATE TABLE TB_ARTIGO (
    ID_ARTIGO BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    DS_TITULO VARCHAR(255) NOT NULL,
    DS_RESUMO VARCHAR(2000),
    CD_ANO_PUBLICACAO INT,

    ID_REPOSITORIO BIGINT NOT NULL,

    CONSTRAINT PK_ARTIGO PRIMARY KEY (ID_ARTIGO),

    CONSTRAINT FK_REPOSITORIO_ARTIGO
        FOREIGN KEY (ID_REPOSITORIO)
        REFERENCES TB_REPOSITORIO (ID_REPOSITORIO)
        ON DELETE RESTRICT
 
);

CREATE TABLE TB_AVALIACAO (
    ID_AVALIACAO BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    DS_PARECER VARCHAR(2000),
    ST_AVALIACAO VARCHAR(20) NOT NULL, -- Valores: 'APROVADO', 'REJEITADO', 'PENDENTE', 'EM_REVISAO'
    DH_AVALIACAO TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    ID_PESQUISADOR_AVALIADOR_1 BIGINT NOT NULL,
    ID_PESQUISADOR_AVALIADOR_2 BIGINT NOT NULL,
    ID_REVISAO BIGINT NOT NULL,
    ID_ARTIGO BIGINT NOT NULL,

    CONSTRAINT PK_AVALIACAO PRIMARY KEY (ID_AVALIACAO),
    CONSTRAINT CK_AVALIACAO_STATUS CHECK (ST_AVALIACAO IN ('APROVADO', 'REJEITADO', 'PENDENTE', 'EM_REVISAO')),
    CONSTRAINT CK_AVALIACAO_PARES_DISTINTOS CHECK (ID_PESQUISADOR_AVALIADOR_1 <> ID_PESQUISADOR_AVALIADOR_2),

    CONSTRAINT FK_PESQUISADOR_AVALIACAO_AV1
        FOREIGN KEY (ID_PESQUISADOR_AVALIADOR_1)
        REFERENCES TB_PESQUISADOR (ID_PESQUISADOR)
        ON DELETE RESTRICT,
    
    CONSTRAINT FK_PESQUISADOR_AVALIACAO_AV2
        FOREIGN KEY (ID_PESQUISADOR_AVALIADOR_2)
        REFERENCES TB_PESQUISADOR (ID_PESQUISADOR)
        ON DELETE RESTRICT,

    CONSTRAINT FK_ARTIGO_AVALIACAO
        FOREIGN KEY (ID_ARTIGO)
        REFERENCES TB_ARTIGO (ID_ARTIGO)
        ON DELETE RESTRICT,

    CONSTRAINT FK_REVISAO_AVALIACAO
        FOREIGN KEY (ID_REVISAO)
        REFERENCES TB_REVISAO (ID_REVISAO)
        ON DELETE RESTRICT
);

CREATE TABLE TB_CRITERIO (
    ID_CRITERIO BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    DS_DESCRICAO VARCHAR(2000) NOT NULL,
    TP_CRITERIO VARCHAR(8) NOT NULL, -- Valores: 'INCLUSAO' e 'EXCLUSAO'
    ID_REVISAO BIGINT NOT NULL,

    CONSTRAINT PK_CRITERIO PRIMARY KEY (ID_CRITERIO),
    CONSTRAINT CK_CRITERIO_TIPO CHECK (TP_CRITERIO IN ('INCLUSAO', 'EXCLUSAO')),

    CONSTRAINT FK_REVISAO_CRITERIO_DEFINE
        FOREIGN KEY (ID_REVISAO)
        REFERENCES TB_REVISAO (ID_REVISAO)
        ON DELETE RESTRICT
);

CREATE TABLE TB_ESTATISTICA (
    ID_ESTATISTICA BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    DS_METRICA VARCHAR(100) NOT NULL,
    VL_VALOR DECIMAL(18, 4),
    ID_ARTIGO BIGINT NOT NULL,
    
    CONSTRAINT PK_ESTATISTICA PRIMARY KEY (ID_ESTATISTICA),

    CONSTRAINT FK_ARTIGO_ESTATISTICA_GERA
        FOREIGN KEY (ID_ARTIGO)
        REFERENCES TB_ARTIGO (ID_ARTIGO)
        ON DELETE RESTRICT
);

-- Criação das relações/tabelas associativas (RL_)

CREATE TABLE RL_PESQUISADOR_REVISAO (
    ID_PESQUISADOR BIGINT NOT NULL,
    ID_REVISAO BIGINT NOT NULL,
    CONSTRAINT PK_PESQUISADOR_REVISAO PRIMARY KEY (ID_PESQUISADOR, ID_REVISAO),

    CONSTRAINT FK_PESQUISADOR_RL_PESQ_REV
        FOREIGN KEY (ID_PESQUISADOR)
        REFERENCES TB_PESQUISADOR (ID_PESQUISADOR)
        ON DELETE RESTRICT,
    
    CONSTRAINT FK_REVISAO_RL_PESQ_REV
        FOREIGN KEY (ID_REVISAO)
        REFERENCES TB_REVISAO (ID_REVISAO)
        ON DELETE RESTRICT
);

-- Criação da tabela de Auditoria (prefixo TA_)
CREATE TABLE TA_AUDITORIA (
    ID_AUDITORIA BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    DH_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TP_OPERACAO CHAR(1) NOT NULL, -- Valores: I (Insert), U (Update), D (Delete)
    DS_SCHEMA_NOME VARCHAR(100) NOT NULL,
    DS_TABELA_NOME VARCHAR(100) NOT NULL,
    NM_USUARIO_BD VARCHAR(100) NOT NULL DEFAULT CURRENT_USER,
    NM_USUARIO_APLICACAO VARCHAR(100), 
    NM_TERMINAL VARCHAR(100), 
    DS_DADOS_ANTIGOS TEXT,
    DS_DADOS_NOVOS TEXT,
    DS_QUERY_COMPLETA TEXT,

    CONSTRAINT PK_AUDITORIA PRIMARY KEY (ID_AUDITORIA),
    CONSTRAINT CK_AUDITORIA_OPERACAO CHECK (TP_OPERACAO IN ('I', 'U', 'D'))
);
