CREATE INDEX IX_RL_PESQ_REVISAO_ID_PESQUISADOR ON RL_PESQUISADOR_REVISAO (ID_PESQUISADOR);
CREATE INDEX IX_AV_ID_REVISAO ON TB_AVALIACAO (ID_REVISAO);
CREATE INDEX IX_CRIT_ID_REVISAO ON TB_CRITERIO (ID_REVISAO);
CREATE INDEX IX_ART_ID_REPOSITORIO ON TB_ARTIGO (ID_REPOSITORIO);

CREATE INDEX IX_AV_PESQ_AVALIADOR_STATUS ON TB_AVALIACAO (ID_PESQUISADOR_AVALIADOR_1, ST_AVALIACAO, ID_ARTIGO);
CREATE INDEX IX_ARTIGO_ANO_REPOSITORIO ON TB_ARTIGO (CD_ANO_PUBLICACAO, ID_REPOSITORIO) INCLUDE (ID_ARTIGO);
CREATE INDEX IX_REVISAO_DT_CONCLUSAO ON TB_REVISAO (DT_CONCLUSAO);
CREATE INDEX IX_AV_ARTIGO_DH_AVALIACAO ON TB_AVALIACAO (ID_ARTIGO, DH_AVALIACAO DESC);
